{
  "modified": "2018-01-04T19:57:01Z",
  "published": "2014-12-12T11:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2014-9365",
  "aliases": [
    "PSF-2014-7"
  ],
  "details": "The HTTP clients in the (1) httplib, (2) urllib, (3) urllib2, and (4) xmlrpclib libraries in CPython (aka Python) 2.x before 2.7.9 and 3.x before 3.4.3, when accessing an HTTPS URL, do not (a) check the certificate against a trust store or verify that the server hostname matches a domain name in the subject's (b) Common Name or (c) subjectAltName field of the X.509 certificate, which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.7.9"
            },
            {
              "fixed": "3.10.0-alpha1"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue22417"
    },
    {
      "type": "WEB",
      "url": "https://www.python.org/dev/peps/pep-0476/"
    }
  ]
}