{
  "modified": "2023-05-24T00:00:00Z",
  "published": "2020-07-13T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2019-20907",
  "aliases": [
    "PSF-2020-2"
  ],
  "details": "In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.5.10-rc1"
            },
            {
              "introduced": "3.6.0-alpha1"
            },
            {
              "fixed": "3.6.12"
            },
            {
              "introduced": "3.7.0-alpha1"
            },
            {
              "fixed": "3.7.9"
            },
            {
              "introduced": "3.8.0-alpha1"
            },
            {
              "fixed": "3.8.5"
            },
            {
              "introduced": "3.9.0-alpha1"
            },
            {
              "fixed": "3.9.0-beta5"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue39017"
    }
  ]
}