{
  "modified": "2023-06-30T00:00:00Z",
  "published": "2022-04-13T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2015-20107",
  "aliases": [
    "PSF-2022-1"
  ],
  "details": "In Python (aka CPython) up to 3.10.8, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments). The fix is also back-ported to 3.7, 3.8, 3.9",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:L"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.16"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.16"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.9.16"
            },
            {
              "introduced": "3.10.0"
            },
            {
              "fixed": "3.10.8"
            },
            {
              "fixed": "3.11.0-beta4"
            },
            {
              "introduced": "3.11.0"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue24778"
    }
  ]
}