{
  "modified": "2023-05-24T00:00:00Z",
  "published": "2020-01-30T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2020-8492",
  "aliases": [
    "PSF-2020-8"
  ],
  "details": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.5.0"
            },
            {
              "fixed": "3.5.10"
            },
            {
              "introduced": "3.6.0"
            },
            {
              "fixed": "3.6.11"
            },
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.8"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.3"
            },
            {
              "fixed": "3.10.0-alpha1"
            },
            {
              "introduced": "3.10.0"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue38826"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue39503"
    }
  ]
}