{
  "modified": "2025-06-26T16:49:31Z",
  "published": "2014-11-16T01:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2014-2667",
  "aliases": [
    "PSF-2014-5"
  ],
  "details": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue21082"
    }
  ]
}