{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2021-01-19T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2021-3177",
  "aliases": [
    "PSF-2021-3"
  ],
  "details": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.13"
            },
            {
              "fixed": "3.7.10"
            },
            {
              "fixed": "3.8.8"
            },
            {
              "fixed": "3.9.2"
            },
            {
              "fixed": "3.10.0-alpha5"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/cve-2021-3177"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue42938"
    }
  ]
}