{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2022-03-04T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2021-3737",
  "aliases": [
    "PSF-2022-7"
  ],
  "details": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.14"
            },
            {
              "fixed": "3.7.11"
            },
            {
              "fixed": "3.8.11"
            },
            {
              "fixed": "3.9.6"
            },
            {
              "fixed": "3.10.0-beta2"
            },
            {
              "fixed": "3.11.0-alpha1"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/CVE-2021-3737"
    },
    {
      "type": "ADVISORY",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1995162"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue44022"
    }
  ]
}