{
  "modified": "2021-03-12T12:06:36Z",
  "published": "2020-07-04T22:54:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2020-15523",
  "aliases": [
    "PSF-2020-4"
  ],
  "details": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.5.0"
            },
            {
              "fixed": "3.5.10"
            },
            {
              "introduced": "3.6.0"
            },
            {
              "fixed": "3.6.12"
            },
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.9"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.4"
            },
            {
              "fixed": "3.9.0-beta5"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.10.0-alpha1"
            },
            {
              "introduced": "3.10.0"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue29778"
    }
  ]
}