{
  "modified": "2023-05-16T00:00:00Z",
  "published": "2020-06-18T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "CVE-2020-14422",
  "aliases": [
    "PSF-2020-3"
  ],
  "details": "Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in the IPv4Interface and IPv6Interface classes, which might allow a remote attacker to cause a denial of service if an application is affected by the performance of a dictionary containing IPv4Interface or IPv6Interface objects, and this attacker can cause many dictionary entries to be created. This is fixed in: v3.5.10, v3.5.10rc1; v3.6.12; v3.7.9; v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1; v3.9.0, v3.9.0b4, v3.9.0b5, v3.9.0rc1, v3.9.0rc2.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.5.10"
            },
            {
              "fixed": "3.6.12"
            },
            {
              "fixed": "3.7.9"
            },
            {
              "fixed": "3.8.4"
            },
            {
              "fixed": "3.9.0-beta4"
            },
            {
              "fixed": "3.10.0-alpha1"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue41004"
    }
  ]
}