{
  "modified": "2022-04-19T17:32:41Z",
  "published": "2019-10-31T20:05:57Z",
  "schema_version": "1.5.0",
  "id": "CVE-2019-5010",
  "aliases": [
    "PSF-2019-8"
  ],
  "details": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
  "affected": [
    {
      "package": {
        "ecosystem": "DHI",
        "name": "python",
        "purl": "pkg:dhi/python"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "2.7.0"
            },
            {
              "fixed": "2.7.16"
            },
            {
              "introduced": "3.4.0"
            },
            {
              "fixed": "3.4.10"
            },
            {
              "introduced": "3.5.0"
            },
            {
              "fixed": "3.5.7"
            },
            {
              "introduced": "3.6.0"
            },
            {
              "fixed": "3.6.9"
            },
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.3"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue35746"
    },
    {
      "type": "WEB",
      "url": "https://blog.talosintelligence.com/2019/01/vulnerability-spotlight-pythonorg.html"
    }
  ]
}